[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "psij-python",
    "proxystore",
    "psycopg2",
    "paramiko",
    "funcx",
    "psutil"
]
build-backend = "setuptools.build_meta"
